### ISSUE TITLE
Opyat pyos

### ISSUE THREAD

**Issue by PyotrSpetsnaz** [Koroed022/ForkMANIA#4]
Darova. Your token is AAFQg***************bPYnXu1A.
I ukral it again. I will ispolzowat your bot for my korystnie purpose hahahahahahahahahahahah. Sosatt

**Comment by PyotrSpetsnaz** [comment]
I mean udoli prosto sorry

**Comment by Koroed022** [comment]
Dont lie me im not a dog
Fork u latherman
